---
title: "paperTemplate"
output: html_document
---




output: 
  pdf_document:
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms2.tex
title: "An Example Article"
thanks: 
Current version: `r format(Sys.time(), '%B %d, %Y')`."
author:
- name: Megan Patsch
  affiliation: University of Iowa
abstract: " "
keywords: " "
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
spacing: single
bibliography: \dummy{`r file.path(getwd(), list.files(getwd(), "bib$"))`}
biblio-style: apsr
citecolor: black
linkcolor: black
endnote: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load all the packages you will use below 
library(dotwhisker)
library(tidyverse)
```

#Introduction
Anti-government rebel groups often form to challenge governments when members perceive themselves to be excluded, oppressed, or underrepresented.  These groups are known for their use of violence towards the state and sometimes civilians.  However, the traditional view of rebel groups as homogenous, militant organizations is of limited value for researchers seeking to understand rebels.  During war, these organizations often form their own governance institutions.  The most complex systems levy taxes, provide public goods, operate independent judicial systems, and hold elections.  The least complex systems do little more than use violence to achieve their goals.  Between 1950 and 2006, the world witnessed 127 civil wars (Huang 2016).  Following conflict, forty-eight states (38%) implemented power-sharing agreements with rebel groups as part of their peace process (Mukherjee 2006; Hartzell and Hoddie 2003).  
Power-sharing builds on democratic ideals such as cooperation and inclusion, making it a promising and idealistic solution to war.  But the growing interest in power-sharing is backed by limited and troubling findings in the literature.  Rebel groups specialize in using violence as a key tactic in achieving their goals, yet up to 43% of these groups will transition into politics at some point (Jones and Libicki 2008).  These transitions are not always successful, and do not preclude the continued use of violence or the development of a terrorist wing of the party.  Research indicates that 44% of societies with power-sharing in place will see conflict recurrence within just two years of the agreement’s implementation (Mukherjee 2006).  Despite the alarming rate of failure, power-sharing continues to be lauded as a cure for violent rebellions and insurgencies.     
Why are these agreements so unsuccessful?  Current research on power-sharing has not produced a satisfactory answer.  Researchers have focused their attention on post-conflict elections in power-sharing societies, levels of democratization, or the group’s transformation process.  Yet, the question of what exactly goes wrong within these shared governments remains unanswered.  Power-sharing provisions mean that rebel groups must transition from militant organizations to political ones. This is something they do with varying levels of experience regarding democratic governance and institutions.  One reasons for the failure of power-sharing could be this difficult transition; newly elected rebels may lack the knowledge and experience to successfully operate in these shared governments.  
I use Huang’s (2016) Rebel Governance Dataset (RGD) and power-sharing data from both Mukherjee (2006) and Hartzell and Hoddie (2003) to test whether rebels-turned-politicians with previous governing experience have more peaceful post-conflict regimes.  If we hope to establish more peaceful post-conflict societies and institutions, we must understand the failings in our current processes.  One severely understudied factor is the role of rebel groups in post-conflict governance.  This research seeks to remedy that gap.  I first outline the existing literature about both power-sharing and rebel group transitions, then highlight recent findings about rebel governance.  I then explain my hypotheses, data, and methods before concluding with a brief analysis of these results and what research questions future work may address.

#Rebel Movements and Power-sharing
Power-sharing has become an increasingly popular component of peace agreements (Hartzell and Hoddie 2003; Mukherjee 2006; Ottmann and Vullers 2015).  It is generally viewed as a tool which blends liberal ideas about institutions and political inclusion together for former rebels and their opposition.  In theory, power-sharing should address many of the concerns that can lead rebels to use violence in the first place.  It provides an outlet to address grievances, promotes inclusion and cooperation, and can formally divide territory or resources.  Third parties may even be used to monitor post-conflict processes with former rebels and ensure that they receive the promised outcomes (Hartzell and Hoddie 2003).  
The political roles outlined by these agreements frequently offer rebels high-level positions in the government.  In nearly half of all power-sharing agreements, former rebels were given cabinet positions or seats in the national parliament (Ottmann and Vullers 2015).  This should mean that members and supporters of the rebel group can voice their needs through official political channels including elections, rather than using violent means.  Despite the hopeful premise of power-sharing, it seems insufficient for maintaining peace.  The mere presence of rebels in national assemblies does not extend the duration of peace after war.  The inclusion of rebels in legislative bodies does not decrease the likelihood of conflict recurrence (Marshall and Ishiyama 2016).  This evidence suggests a disconnect between the expectations of power-sharing and the reality for governments who implement it.        
	Former rebels can be unpredictable actors once elected in the new government.  Consider UNITA, an Angolan rebel group who transitioned into a prominent political party following the end of the Angolan civil war.  Their early political strategy seemed to be one of non-participation.  Elected officials from UNITA chose to boycott the electoral process, despite achieving earlier victories at the polls (Vines and Oruitemeka 2008).  RENAMO, in Mozambique, was a rebel movement at war with the government.  They similarly used intentional non-participation strategies after winning seats in elections (Beresford 1994).  In one instance, RENAMO boycotts led to insufficient attendance to achieve quorum in regional assemblies, but in the national assembly REANMO’s opposition was able to reach quorum and vote without a single RENAMO member present (“Dhklama Maintains Parlimentary Boycott” 2015).  These are curious choices for UNITA and RENAMO to make: to accept the terms of power-sharing, win elections, and then actively choose inaction within the government.  Does this inaction beget future violence?  Despite inclusion in governing processes, this kind of behavior inhibits policy change in favor of the rebels and their supporters.  In UNITA, officials’ decisions to boycott runoff elections did indeed result in a return to war (Vines and Oruitmeka 2008).  What drove their behavior towards abstention is unclear, though both UNITA and RENAMO voiced displeasure with the election process.  
	Common practice in power-sharing research considers an agreement to have failed if conflict resumes after two years (see Doyle and Sambinas 2000; Mukherjee 2006).  However, in practice, the rate of failure continues to increase even after the first 24 months have passed.  According to Mukherjee (2006), nearly 20% of political power-sharing agreements fail within the first two years.  Another 39% fail in less than eight years.  The remaining agreements fail within fifteen years.  This means that research focused on the two-year time frame for agreement failure is missing most cases of conflict recurrence.  The continued prevalence of these agreements is troubling given how flawed they seem to be in practice.  There are many potential points of vulnerability in the process of creating and implementing these new governing systems, and a significant number of these concerns are specifically related to the rebel groups themselves.  As these organizations transition from militant groups to political parties, they must learn to translate their skills and experience in new ways (De Zeeuw 2008). 
	Research on power-sharing and conflict recurrence has focused largely on agreement provisions or the means by which the conflict ended as the source of failure.  Hartzell and Hoddie (2003) show that the most successful power-sharing agreements have provisions for power-sharing across more than one dimension.  Societies where power-sharing is restricted to only the political or military arenas, for example, are likely to see failure at a higher rate than societies which share power in both.  Mukherjee (2006) suggests that power-sharing success is influenced most by decisive victory in conflict.  He argues that a clear victory shifts the bargaining process and support for agreements amongst civilians and supporters alike.  Power-sharing is most durable when one party ‘wins’ the conflict.    
	Current power-sharing literature often fails to address the potential incompatibility of rebel groups and political parties.  Literature on rebel group transformation studies one set of concerns: can these organizations alter their goals and practices successfully (De Zeeuw 2008)?  But power-sharing literature often assumes the transformation is both complete and successful.  The hypotheses tested here draw on both literatures, by including measures for rebel group knowledge and skills as well as post-conflict outcomes.  Power-sharing success or failure alone does not tell us about the rebel groups’ ability to govern.  These groups can be dangerous, are often powerful, and generally have legitimate grievances.  Previous experience with wartime governance may shed some light on this, as rebels enter power-sharing agreements with varying levels of experience in such roles.
	Not all rebel groups are able to transform their organizations successfully into political parties.  One of the first challenges they face is maintaining membership despite accepting the terms of a peace agreement with their former enemy.  Frustrated and angry members may decide to defect from the rebel’s political organization, costing them necessary electoral votes and community support.  The party itself will need to ensure continued access to funding, and sources who gave money to the war may not be supportive of the group’s new role in politics.  Leaders must also adjust typically strict hierarchical relationships that were efficient during the conflict, to ones with more democratic input and participation (Manning 2004).  Each step made by the former rebels risks alienating past supporters and creating new political challenges for themselves in the future.
	In order to make their transformation “official” rebel groups often must take part in a process of demilitarization.  This structural change serves many purposes.  It entails relinquishing weapons and dissolving military command structures.  As part of their peace agreement, some groups will blend their military wing into the state’s forces rather than completely dissolving it.  Rarely groups will be allowed to maintain their forces with autonomy, though occasionally a rough framework is allowed to survive as a security guarantee.  In most cases, the group is asked to cede all military power as a sign of good faith and a gesture of pacific cooperation for the future (Lyons 2005).  Without these steps, the probability of returning to war is significantly higher than if the rebels do not demilitarize (Kovacs 2008; Wiegand 2010).  Former rebels must learn to translate their ideas from military goals to policy preferences.
	This transition can be one of the most difficult for groups to make.  Goals need to be redefined, party platforms must be developed, and member support must be gained.  In order to see successful policy outcomes, these new political actors must learn to cooperate with former enemies and accept compromises (Weigand 2010).  De Zeeuw (2008) argues that political transformations are often incomplete.  He identifies a range of outcomes for groups attempting this change, from complete success, to façade transformations, to partial ones.  The skills of war are not necessarily skills of peace; yet many groups maintain the same leadership during both war and power-sharing governance.  This is a useful strategy in terms of keeping the group’s broader base of support satisfied, but it may have consequences on their ability to function as a successful political entity and not resume their violent ways.    
During conflict, rebels often create their own quasi-governmental structures which provide services and organization for their members.  Some rebel groups have more sophisticated systems, which build institutions, tax civilians, and even operate police forces.  Others are quite minimal.  Research indicates that rebel groups often function in highly hierarchical or authoritarian ways (Kovacs 2008).  But the nature of these governing institutions and practices may actually depend on the rebels’ funding sources.  Groups with more resources and money at their disposal are able to establish more complex systems of governance.  In particular, rebel groups with high levels of civilian funding build greater numbers of institutions.  
The decision of what kind of governing institutions to create and services to provide is strategic, and is made with political, ideological, economic, and social concerns in mind (Huang 2016).  Manpilly (2011) suggests that rebel governance may be a function of rebel leader preferences and the interaction of such groups with other social service actors in society.  This means that groups with high levels of political support from civilians are more likely to have experience in building institutions for the people, which is a departure from the assumption that rebel groups are almost entirely focused on survival and the use of violence (Huang 2016).  Some groups use public goods and services to erode the legitimacy of the state and increase the perceived legitimacy of the rebel group’s goals.  By providing healthcare and education to non-member populations, rebels are able to fulfill a role traditionally filled by the state (Terostra and Frerks 2017).  The Eritrean People’s Liberation Front (EPLF) began as a violent separatist movement, but during a decades-long conflict they built an organization which provided Ertireans with healthcare and education.  More than 1.6 million people were treated at EPLF medical facilities by the war’s end, and an additional 10,000 received literary training because of the rebels (Stewart 2018).  Some rebel groups make efforts to establish institutions and offer similar services, but are unable to maintain them and may even encounter backlash from civilian communities when efforts fail (Manpilly 2011).  Rebels who have more experience with their own governance systems may have an easier time transition to post-conflict power-sharing roles.
	One possible reason for former rebels’ struggles in power-sharing suggests that they lack the knowledge to perform well within these democratic institutions (Lyons 2005).   Navigating the institutions and behaviors required to operate within official state governments requires both an acceptance of their legitimacy and an understanding of how they function.  Rebel groups by definition have experience with violence, but not necessarily governance.  This could contribute to the lingering appeal of violence as a means of achieving the group’s goals, particularly if the power-sharing government is slow to reach decisions or the group continues to feel excluded from the process.  Regardless of how fully the group transforms, violence will remain a possible tool at their disposal.  Huang’s (2016) work demonstrates that rebels could potentially bring more experience in governance to the bargaining table than previously considered.  Literature on rebel group transformation often points to political inexperience as a major struggle for transitioning parties (see Wiegand 2010; Manning 2004; De Zeeuw 2008).  However, this new dataset sheds light on how knowledgeable rebels truly are or are not when it comes to understanding political systems.  If rebel organizations are moderately experienced with the process of governance, that would mean that inaction, as seen with RENAMO and UNITA, is not the result of inexperience or uncertainty.  It could instead be a strategic decision towards unexpected ends.  Previously, inaction was assumed to be the result of inexperience or frustration, leaving rebels with the choice of accepting political gridlock or returning to war.  This new data suggests that this may be an oversimplification of rebel motivations and skills.  These are assumptions that must be tested.  I expect that previous experience in governing institutions and processes will lead to longer periods of peace during power-sharing.
Rebel groups who established legal systems to govern their membership and territory seem to demonstrate a base-level understanding of key components of democracy.  In particular, the presence of a rebel police force is demonstrative of a more complex system that both establishes and enforces its own legal code.  The presence of a legal system shows a basic level of political rights for those under the rebel’s governance.  Rebels are able to provide an alternative to current state systems in a way which develops its own sense of legitimacy.  Given that these groups often form as the result of grievances, or societal and political inequalities, this means that rebels are providing an invaluable alternative to the status quo (Huang 2016).  Rebels who develop these systems are using skills beyond those traditionally associated with waging war--skills which should serve them well in power-sharing post-war politics.  I expect that rebel groups who exhibit this level of experience and political sophistication will be less likely to return to war, because they are more willing to accept the legitimacy of their new government and have an understanding of how to work within the legal system.     

#Hypotheses
Hypothesis 1: Rebel groups who maintained legal systems and police forces will have a lower likelihood of conflict recurrence in power-sharing governments. 
	The presence of health and education services is indicative of groups whose focus extends beyond organizational survival and violence.  The distribution of these services signals that rebels are interested in the well-being of members and society.  Organizational transformation literature often regards rebel groups as being narrowly interested in a specific set of goals for which they employ military tactics (Weigand 2010).  However, the ability and willingness to educate and provide health services to civilians goes beyond this.  It shows an extra skill set and potential for expertise beyond making war.
	Services such as health and education, or even law and order, create connections between civilian populations and rebel groups.  They provide a way for rebels to interact with the broader population, and even to benefit from these relationships.  In exchange for services such as these, rebels may receive intelligence or logistical support, civilian funding, even weapons or shelter (Huang 2016).  These reasons drive the creation of key institutions that mimic those seen in the official “legal” societies.  This demonstrates a level of sophistication and understanding of processes and bureaucracies beyond hierarchical military ones.  These kinds of services may make post-war states more authoritarian, or more reliant on patronage.  However, the question I am seeking to answer here is not one of good governance; rather I am seeking to find the connection between rebel governance during war and their ability to govern after war.  I expect that rebel groups who are able to build educational and health service systems will be less likely to return to violence.
Hypothesis 2: Rebel groups who maintained educational and health systems will have a lower likelihood of conflict recurrence in power-sharing governments. 
	A particularly challenging element of the transition to political parties involves participation in elections.  Rebels do not generally have extensive knowledge in running campaigns, winning elections, or accepting the legitimacy of results (Lyons 1999).  However, the RGD shows that during war time, some rebel groups run their own elections for leadership of different governing bodies.  Experience winning and participating in elections could be an important part of accepting power-sharing as a politician and leaving violence behind.  
	There is evidence supporting the idea that rebel state-building acts to mobilize civilian populations.  Huang (2016) argues that greater numbers of institutions and civilian input can generate high political mobility from the public.  In a sense, holding popular elections for rebel governance is a practice run of sorts for later elections with the official state government.  If rebel leaders have previously accepted the legitimacy of an election process for political roles, they should be more likely to acquiesce in the power-sharing regime.  These early elections provide experience for the rebels which should translate into willingness to work peacefully later on.  Having already developed a pool of supporters through previous governance institutions, they will also likely have a baseline of support which less experienced rebel groups lack.  Huang (2016) contends that some rebel groups rely on coercion rather than free-will participation under rebel regimes.  However, this issue seems more prevalent with questions of rebel funding, not elections.  Though it is important to note this information, it does not influence the research in this paper.  I expect that rebel groups who hold elections during war will have a higher probability of maintaining peace.
Hypothesis 3:  Rebel groups who held elections during civil war will have a lower likelihood of conflict recurrence in power-sharing governments. 

#Data and Methods (revisit)
Data and Methods        
	The growing interest and resultant literature on rebels and power-sharing has made possible new strategies for studying this subject.  To establish the experience level of rebels I used Huang’s (2016) Rebel Governance Dataset (RGD).  This data provides background information on how sophisticated each rebel group’s state-building and governance was during war.  It includes measures of both funding and governance, though the focus of this research is solely on the governing variables.  It is from this dataset that the universe of cases and independent variables are derived.  The presence of each kind of system is a dichotomous variable; 1 if it was present in the rebel wartime governance structure and 0 if it was not.
	Conflict recurrence is measured with the UCDP Armed Conflict Dataset.  This classifies conflict recurrence when there are 25 battle-related deaths in a given year, when the state is one party in the conflict (Gleditsch et al. 2002).  Because these are civil conflicts between rebel groups and states, this measure will accurately capture the point when conflict resumes.  When conflict is present, it will be coded as a 1.  When conflict is not present, it will be coded as a zero.  Each year after after a power-sharing agreement is implemented will be coded as either a zero or a 1.    
To establish which states had power-sharing agreements with former rebels, I used the cases enumerated by Mukherjee (2006) and Hartzell and Hoddie (2003).  Mukherjee’s dataset included mainly political power-sharing agreements, whereas Hartzell and Hoddie included more varied ones.  By including cases from both Mukherjee and Hartzell and Hoddie, I will be able to test a wider range of possible experience and expertise.  I have considered the following types of power-sharing: political, institutional, and military.  This extension added four cases to the study: Angola (1994), Azerbaijan (1994), Dominican Republic (1965), and Georgia (1994).  As Hartzell and Hoddie explain, the difference between political power-sharing and other kinds can be difficult to parse out.  In many instances, the agreements share similar provisions, but are coded in one category over another out of necessity.  It is my hope that by including both sets I can capture the broadest possible application of relevant power-sharing.  The full list of cases is given in Table 1.   
#Add Table 1: Power-shaing cases
There were 48 instances of power-sharing in the Rebel Governance Dataset from 1950 to 2006.  Of these, 21 states (44%) saw conflict recurrence within two years.  The cases where power-sharing failed to promote peace are listed in Table 2.  In 27 cases (56%), peace endured for more than two years.  Because the two-year cutoff is prevalent in the power-sharing literature as an accepted measure of “success” versus “failure,” that was used here (see Doyle and Sambanis 2000; Mukherjee 2006).  The rate of power-sharing failure within these cases is similar to the rates found by Mukherjee (2006) and Hartzell and Hoddie (2003). 
#Add Table 2:Failed Power-sharing
#finish 





## Citations
Want to cite something?

1. Find your cite key in your bib file.
1. Put an @ before it, like @Solt2017, or whatever it is
1. @Solt2017 creates an in-text citation
1. [@Herndon2014] creates a parenthetical citation

As @Gelman2014 note, the garden of forking paths can pose problems for researchers even when they are acting in good faith.

## Other Common Things

> This will create a block quote, if you want one.
Dropping a footnote is easy.^[See? Not hard at all.]

