
---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: no
    template: svm-latex-ms2.tex
title: 'Breaking the Power-Sharing Promise: Protests in Post-conflict Society'
author:
- affiliation: University of Iowa
  name: Megan Patsch
date: "`r format(Sys.time(), '%B %d, %Y')`"

citecolor: black
biblio-style: apsr
endnote: no
fontsize: 11pt
keywords: 'rebels, power-sharing, post-conflict, protest '
linkcolor: black
bibliography: \dummy {`r file.path(getwd(), list.files(getwd(), "bib$"))`}
spacing: single
abstract: 'Increasingly, rebel groups are being incorporated into legitimate governments
  as part of liberal peace processes designed to facilitate inclusion (@hartzell_institutionalizing_2008).  As
  a result, former rebels are given political offices in post-conflict governments.  Existing
  research often treats all rebel groups as similar entities in both pre-and post-conflict
  societies.  However, research in recent years has made efforts to establish a more
  nuanced understanding of these groups and has highlighted an intriguing trend; rebel
  groups may provide public services and create their own bureaucracies in an attempt
  to gain support, increase legitimacy, or even decrease the state’s legitimacy during
  war (see @stewart_civil_2018, @terpstra_rebel_2017).  These behaviors have unexplored
  implications in the post-conflict setting.  How do these practices affect post-conflict
  governments?  I test the effect of power-sharing with rebels on political protests
  from 1980 to 2018 and find that political inclusion of rebels generally as a negative
  effect on protests.  However, power-sharing with rebels who held wartime elections
  can increase the likelihood of protest after war. '
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load all the packages you will use below 
#install.packages("tinytex")
library(readxl)
RgdMmFhCorrected <- read_excel("RgdMmFhCorrected.xlsx")
View(RgdMmFhCorrected)


library("MASS")
library(ggplot2)
library(mfx)
library(dotwhisker)
library(tidyverse)
```

GovernHist <- hist(RgdMmFhCorrected$govern,
              main="Histogram for Governance Institutions" ,
              xlab="Number of Institutions" ,
              border="light blue" ,
              col="blue") 
 
colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Power-Sharing"] <- "Powersharing" 
colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Rebel Governance Score"] <- "RebelGovernance" 
 colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Government Victory"] <- "GovernmentVictory"
 colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Rebel Victory"] <- "RebelVictory"
colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Settlement"] <- "Settlement" 
 colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="coup"] <- "Coup"
 colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Civil Liberties"] <- "CivilLiberties"
colnames(RgdMmFhCorrected)[colnames(RgdMmFhCorrected)=="Political Rights"] <- "PoliticalRights" 
 
 
 
 
              
m1 <- negbinmfx(data = RgdMmFhCorrected, protest1 ~ Powersharing + RebelGovernance + GovernmentVictory + RebelVictory + Settlement + Coup + CivilLiberties + PoliticalRights + t + t2 + t3, clustervar1 = "region")
summary(m1$fit)
m1$mfxest

Figure2 <- as.data.frame(m1$mfxest) %>% transmute(term = rownames(.), estimate = `dF/dx`, std.error = `Std. Err.`) %>% dotwhisker::dwplot() 


m3 <- negbinmfx(data = RgdMmFhCorrected, protest1 ~ Powersharing*elect + RebelGovernance + GovernmentVictory + RebelVictory + Settlement + Coup + CivilLiberties + PoliticalRights + t + t2 + t3, clustervar1 = "region")
summary(m2$fit)
m2$mfxest

Figure3 <- as.data.frame(m2$mfxest) %>% transmute(term = rownames(.), estimate = `dF/dx`, std.error = `Std. Err.`) %>% dotwhisker::dwplot() 


	

	As civil conflicts approach peaceful resolution, rebel groups are frequently offered power-sharing agreements which utilize democratic principles to alleviate grievances.  Rebel organizations, as a result, are given the opportunity to transition into political life.  Despite the appealingly liberal provisions in power-sharing, these agreements often fail to promote peace [@mukherjee_why_2006].  Success of power-sharing has been measured in the literature in terms of civil war recurrence, but this approach leaves significant uncertainty about lower-level activity in post-war states.  The amount of support that power-sharing governments have, the kind of opposition they face, or even the willingness for former rebels and non-rebel citizens to accept these new governments has been largely unexplored.  
	Power-sharing governments rule over not only former rebels and their supporters, but also the wider population of the state.  In some cases, rebel groups have high levels of perceived legitimacy and governing experience from their wartime efforts.  In others, they do not.  Some groups ran extensive healthcare services, collected taxes, and held elections for leadership positions, but others were limited to military goals alone (@terpstra_rebel_2017).  Do these differences affect post-conflict society?  In this paper, I address this question by exploring the relationship between power-sharing governments and anti-government protests.  

##Rebel Groups
	Research on rebel groups and rebel movements has historically treated all groups as similar to one another.  However, recent literature has been exploring a more nuanced view of such organizations (See @huang_wartime_2016, @stewart_civil_2016, @terpstra_rebel_2017).  Older research tended to view rebel groups as highly hierarchical, predominantly militant, and somewhat one-dimensional.  The expectation was that these groups existed to use violence against the state to achieve a set of goals.  But this is an overly narrow view of such groups, which has limited our ability to understand their transition into post-conflict politics.  New research has insightfully added dimension and highlighted important differences between rebel groups which may have critical implications in the post-war period.
	One critical source of variation in rebel groups is wartime governance.  Though some rebels are focused on military victories and tactics, there is a wide range of governance structures, institutions, and services that other groups provide.  Rebel groups can hold elections, collect taxes, operate police forces, have parliaments and executive offices, provide educational services, or provide healthcare facilities in their communities.  These services are sometimes limited to members who support rebel groups, but may be offered to locals regardless of their support or opposition to rebel goals (@huang_wartime_2016).  The effects of these wartime efforts can be huge.  The Eritrean People’s Liberation Front (EPLF) began as a guerrilla organization with separatist goals.  Over time, however, the developed an extensive system of public goods provision.  Estimates suggest that by the end of the war the EPLF provided medical care to more than 1.6 million people.  They served an additional 10,000 with literacy training (@stewart_civil_2018).  Such behavior by rebels likely has an impact after war.  
	What accounts for this behavior?  Though some research suggests that providing public goods could be a source of recruitment ( @berman_religion_2008), other research indicates that these strategies are used towards different goals.  Open services in particular come with no quid-pro-quo wherein citizens are compelled to join the rebels in exchange for public goods.  One possible goal of rebel services such as these could be legitimacy.  When rebel groups are able to provide security, education, and healthcare to communities it increases views of their legitimacy by locals.  It also helps them to maintain control over territory, which could be necessary for future conflict or as leverage when bargaining for peace (@terpstra_rebel_2017).  Using violence, force, and coercion to control different areas is a resource-heavy drain on rebel groups.  Offering these services, in contrast, is less costly and more effective in the long run.  Increased legitimacy for rebel groups can also diminish the perceived legitimacy of the official state government.  When rebels are able to provide needed goods and services to communities, which the state government cannot then they are able to simultaneously improve their image while chipping away at that of the “official” state (@terpstra_rebel_2017).
	
	
##Power-Sharing
	Power-sharing agreements have been increasingly popular conflict resolution tools in the last few decades (@ottmann_power-sharing_201).  This is because they appeal to liberal ideals such as inclusion, and democracy.  If conflict is caused by political exclusion, grievances, and need then surely the way to alleviate conflictual societies is to provide a political remedy to those issues.  Yet power-sharing agreements, despite being designed around such sources of conflict, fail at alarming rates.  Mukherjee (@mukherjee_why_2006, p.480) conducted one study of 61 cases of power-sharing and found that in 19 cases (approximately 31%) conflict resumed within 6-19 months, in 24 cases (39%) conflict resumed in 67-94 months, and in 18 cases (30%) conflict returned in 95-183 months.  Though the duration of peace was longer in some cases than others, ultimately conflict returned to each case of power-sharing studied by Mukherjee.    
	Power-sharing agreements can offer rebels different incentives and offices.  As part of an agreement, rebels may be incorporated into the state, military, or society in new ways.  There are four main kinds of power-sharing provisions: economic, territorial, military, or political.  (@hartzell_institutionalizing_2008).  Often, these categories will be used in conjunction with one another to address as many grievances as possible.  With economic power-sharing, government-distributed resources may be allocated or regulated in a way which is more equitable for the former rebels.  Military power-sharing provides an alluring security incentive for former rebels, but also presents the challenging of allowing a formerly violent, anti-government groups to retain arms.  Political power-sharing happens in perhaps the most diverse ways.  In some agreements, rebels are allocated specific seats in parliament, or even executive office.  In other cases, former rebels are merely allowed to run for office and thereby given a chance to legislate (Mukherjee 2006).  Agreements which offer multiple forms of power-sharing tend to experience greater peace after implementation (@hartzell_institutionalizing_2008).
	The democratic appeal of power-sharing agreements is paramount.  Inclusion is inherent in these deals, regardless of the specific provisions.  But another important consideration is public support.  When democratic leaders have high levels of political trust, they are able to be more successful (@wang_political_nodate).  It is unclear how much trust power-sharing governments and political actors are able to garner.  As part of the peacetime arrangements, amnesty for crimes committed during war is often given to former rebels and their leadership (@jarstad_war_2008).  This makes the act of reaching an agreement possible, but presents challenges for those in society who prefer a more an approach that appeals to those desiring retribution or justice.  
	In 2016, the Revolutionary Armed Forces of Colombia (FARC) were offered a possible peace deal with the Colombian government after more than 50 years of violent conflict.  One provision of this agreement was amnesty for key members of the organization.  As part of the peace process, a popular vote was used to determine the final agreement.  When put to such a vote, Colombians voted against the deal.  One of the main reasons for this rejection: amnesty (@shifter_will_2016).  A different deal was later accepted which included harsher punishments for members of FARC (@katkov_colombias_2016).  Power-sharing with former rebels who would have been given amnesty was unpopular amongst Colombians.  This vote provides possible insight to society’s preferences and perceptions of rebels.  But not all power-sharing agreements are put to a vote; in many cases once the government declares an agreement completed it is implemented accordingly.
	The promise of power-sharing as a tool for peace is couched in calculated risks.  Democracy, accountability, and representation can be challenged by such agreements.  New power-sharing governments blend former enemies together and ask them to work together effectively enough that policy continues to be made and implemented.  In these societies there is a high risk of government stalemate, which can aggravate the same grievances that led to rebel group formation by failing to produce adequate services and policies.  The way that rebels interacted with society during war can even have an impact on how democratic the post-conflict government is.  If rebels were highly reliant on civilians during the conflict, particularly near the end of it, this can have a positive impact on how democratic the post-conflict government is.  However, if rebel institutions remain active after war ends, the government is likely to be more authoritarian (@huang_wartime_2016).  Additionally, there is a challenge on the individual level: the skills which make an effective wartime rebel leader may not be the same skills that make a strong political leader.  More experience from wartime governance may give some rebels an advantage in political settings. 
	
	
##Post-Conflict
	In the post-conflict era, rebel groups must undergo a transition to become political parties.  These transformations can be challenging.  Groups must transition goals from military aims to policy proposals, expand their support base to gain votes, and find sources of funding for their party.  The transition to political party from rebel group can cost valuable support from previous membership, support which can be challenging to find elsewhere for a party untested at the polls.  Post-conflict elections must also take place, which can be difficult and even violent.  Though post-conflict election are critical for implementing power-sharing agreements and signaling a return to peaceful politics, they can have a detrimental effect.  In some cases, these elections may be the source of conflict recurrence (@keels_oil_nodate 2015).  High levels of political participation may be a sign of highly mobilized and engaged citizens—a possibly dangerous ingredient in a society not far removed from war (@letsa_voting_2017).  However, some research suggests that high turnout is a sign of tacit support for peace agreements (Kumar 1998).  
	The continued implementation of power-sharing agreements presents an interesting paradox: if political inclusion is the remedy for conflictual behavior, why does power-sharing fail at such a high rate?  One of the most understudied aspects of power-sharing is post-conflict societies.  Beyond the likelihood of conflict recurrence, we know little about how well former rebels can govern or how well they are received as government officials.  Given their previous involvement in violence and war, it is possible that they are perceived as illegitimate.  But wartime public goods provisions or democratic behavior may change that perception and increase the likelihood that they are accepted as political officials.  We now know that not all rebel groups are viewed as illegitimate in wartime by the general population (Terpstra and Frerks 2017).  If rebel groups were focused not only on military targets, but also on community wellbeing, can they be integrated into power-sharing governments with less friction?  One possible measure of support or opposition to power-sharing governments is protests.  Protests are one possible sign of mobilized and frustrated citizens 
Protests and Mass Movements
	Protest behavior can have mixed implications in a democratic setting.  Collective mobilization is dependent on shared grievances, social networks, communication ability, and the realm possible actions available.  Tarrow (@tarrow_power_2011) makes the distinction that insurgency is characterized by disruption, which may or may not be associated with mass movements.  Movements which rely too heavily on disruptive behavior are at a higher risk of resorting to violence than those which adopt alternative ways to address their concerns.  One of the most important factors, according to Tarrow (@tarrow_power_2011), is social networks.
	As part of most peace agreements, rebel groups take part in demobilization, disarmament, and reintegration (DDR) processes.  These are often led by the state, but may be facilitated by outside groups involved in conflict resolution with the two sides.  DDR is designed to disarm and demilitarize rebels, making them less of a threat to society and the government.  They also aim to incorporate former rebels into regular social networks and work environments, though the extent to which these goals are pursued varies greatly.  Research has shown that even when DDR programs are otherwise successful, rebel networks remain engaged between individuals who took part in civil wars (@wiegink_former_2015).  The bonds between former rebels are deep; often they live in the same places, socialize regularly, and even work at the same peace-time jobs.  These network connections can prove dangerous if rebel leadership has been coopted by the government, which is highly possible after power-sharing takes effect (Themner 2015).  Essentially: rebel groups remain largely intact socially, even after rebel leaders become political and weapons are eliminated.  If, as Tarrow (tarrow_power_2011) suggests, social networks are the most necessary element for mass mobilization then former rebel groups are in a prime position to be re-engaged.  
	Data regarding public acceptance of power-sharing from non-rebel supporters is limited, but could provide insight on post-conflict protests, as well.  Few agreements are put to public vote; the Colombia deal with FARC is one of the most well-known examples.  For Colombians, willingness to accept FARC as a political entity was met with significant push-back when a referendum vote was first offered in 2016 (@katkov_colombias_2016).  The initial power-sharing agreement was rejected by popular vote, but the Colombian government and FARC continued to pursue an inclusive settlement.  Even after a different deal was accepted, the public strongly opposed FARC as political actors.  Colombians began protesting the former rebels as they organized their new political party and recruited possible candidates.  Opposition to FARC was so strong that they had to suspend campaigns due to threats towards their candidates in 2018 (BBC February 2018).  
	Post-conflict protests are not inherently sinister.  They may signal a healthy democracy, where citizens are using non-violent behavior to demonstrate frustration or disagreement with government behavior.  Even protest by the former rebels can be innocuous.  Sinn Fein, the political party which came out of the Irish Republican Army (IRA), started as a militant organization seeking the reunification of Northern Ireland with Ireland (Feeny 2003).  Sinn Fein ran candidates for local elections long before the new millennium, but their most impactful political work came after they were offered seats in the Northern Ireland Assembly through the Good Friday and St. Andrews Agreements in 1998 and 2006.  After these,  Sinn Fein and their supporters used protests as a means of opposing policy decisions, and they did so within official government channels.  Whereas activity before power-sharing was conducted without regard to legal paperwork or policies, Sinn Fein began to file necessary paperwork for protests once they became a legitimate political party (Moriarty 2008).  In this case, protests were merely another tool in the new party’s political toolbelt. 
	
	
##Hypotheses and Data
	Despite potential uncertainty about the exact meaning behind protests, it seems necessary to first understand whether power-sharing and rebel wartime experience have an influence at all.  Protests are a sign of negative feelings towards the government, which is a useful starting point from which we can understand former rebel’s roles in post-conflict governments and society.    
	For this paper I plan to consider two hypotheses:
	
>H1: Post-conflict societies with former rebel groups in power-sharing will experience protests at lower rates than post-conflict societies without power-sharing.

>H2: Power-sharing agreements where former rebels have more wartime governing experience will have lower levels of protest than those where former rebels have none.

The data I am using for this research comes from three main sources.  Data on wartime rebel governance comes from Huang’s (huang_wartime_2016) Rebel Governance Dataset which contains information on the sophistication of rebel group state-building and governing capacity during war.  Protest data comes from the Mass Mobilization dataset (@clark_mass_2016), which contains data on protests in 162 countries.  This dataset contains information regarding location, protest demands, length of event, and state response but for my purposes I will focus on the number of protests alone.  It holds events from 1990 to 2018.  This gives me a dataset with contains eighteen country-years of protests for countries which experienced civil war termination between 1989 and 2016.  Not all countries exist for the full 18 years, because some were merged into others (i.e. Yugoslavia).  For this study, I included power-sharing agreements which were implemented in 1989 as the effect would still be temporally important to the likelihood of protest.  I also include Colombia, though the date of conflict termination is after the RGD ends.  The Colombian war was active for the time period used in the RGD, so the rebel governance information is included in the dataset.  The protest data was also available, so it seemed pertinent to keep the case in the data.  In total, there are 1,522 observations.     
My dependent variable is the number of protests in each country for each year.  Protests are a count variable, of anti-government mass mobilization.  Because I am looking for a pattern of protest behavior, my model includes two or more protests per year as the lowest threshold.  One protest per year may be tied to a specific event or holiday, and I want to capture ongoing feelings towards power-sharing governments.  The decision to use two protests per year or more is based in the idea that more than one protest a year has meaning for a state.  The choice of two versus three or four is somewhat arbitrary; I simply chose the number which seemed to provide the lowest but still significant threshold for this research.  The main independent variable, power-sharing, is a binary indicator of the presence of a power-sharing arrangement between rebels and the government.  This data comes from Hartzell and Hoddie (@hartzell_institutionalizing_2008, 2003) and Mukherjee (@mukherjee_why_2006, 2006).  Two datasets were used to compile my power-sharing variable because they cover different timespans and have some variation on which conflicts were identified.  By using both sets, I was able to get a more expansive list of power-sharing states.  
Rebel governance is measured as a count variable, where the number of rebel institutions creates a cumulative score for each group.  The term “institutions” is used here to describe governance elements including services, bureaucracy, and political branches.  Rebel governance scores range from 1 to 10, with 10 indicating highest possible number of institutions measured (@huang_wartime_2016).  For example, a group who had healthcare services and police forces would have a score of 2.    It should be noted that this variable does not describe how efficiently these function, or whether their services are restricted to rebel group members or the broader society.  However, the number of institutions is still a useful, if limited, measure of baseline rebel capacity for governance and institutional experience.  The average score for a rebel groups is 3.3.   Institutions include: taxation, elections, an executive branch, police, healthcare, education, legal systems (courts), formal laws, diplomatic exchanges with other countries, and social services including humanitarian efforts (@huang_wartime_2016).  The distribution of rebel governance scores can be seen in Figure 1.  

<center>
[Figure 1: Rebel Governance Score Distribution](C:\Users\Megan\Documents\CMPSPaper\Figure1)
<center>

This model includes binary variables for war termination types: government victory, rebel victory, or settlements.  Because of the unique properties of coups, they are included as a control as well.  These variables come from the RGD (@huang_wartime_2016).  Government repression and regime type can influence the likelihood of protest, so I add a measure to account for freedom in each country.  Measures of political rights and civil liberties are added from Freedom House (Freedom House 2018).  The Freedom House scores are higher when rights are lower, which can produce unclear results in analysis so for the purpose of this research I use inverted scores which give higher values to states with more political rights and civil liberties. To control for the effect of time, I applied cubic polynomials (Carter and Signorino 2010).  This allowed me to easily address the temporal component of my research.  
To test these hypotheses, I first ran a negative binomial regression.  The results for Model 1 can be found in Figure 2.  In this model, power-sharing has a negative and statistically significant effect on the likelihood of protest after war.  This means that my first hypothesis is supported.  Power-sharing seems to decrease antigovernment mobilization in post-war settings.  This fits with the expectation implied in power-sharing and peace agreement research; when agreements allow for more political inclusion there is less public opposition to the government.  

<center>
[Figure 2: Negative Binomial Regression Model 1] (C:\Users\Megan\Documents\CMPSPaper\Figure2)
<center>


Model 1 also shows that the rebel governance score is positive, but not statistically significant.  Government victory, however, was significant.  Conflicts that were ended with a clear government victory are more likely to experience protests after war.  This likely means that citizens with grievances were given little when the war ended, which makes anti-government mobilization a logical conclusion.  Civil liberties are also statistically significant and positive, which means that when societies have more civil liberties protests are more common.  This result fits with literature about free societies and protests.
I then ran the model with an interaction between rebel groups who held wartime elections and were incorporated into power-sharing governments.  These can be found in Figure 3.  When rebel groups who held public elections for wartime offices share political power with post-war governments, there is an increased risk of protest.  This is a particularly curious finding; on one hand, it may indicate that rebels and their supporters are better adapted to democratic behavior.  However, the likelihood of conflict recurrence after power-sharing is implemented is around 45% (@hartzell_institutionalizing_2008).  Protests in this environment may mean that rebel supporters are still unhappy with the state.  Wartime behavior by rebels can shift perceptions of legitimacy away from the state and to the group itself.  This may have a lasting effect on how the government is perceived, though the fact that this result is specific to elections seems to indication a possible democratic behavior component.  Research in the future may consider whether these societies are more or less likely to return to war.  In this model, government victories are still a positive and significant predictor of protests.  Other kinds of conflict termination did not produce significant results in Model 3.  Civil liberties can also increase the likelihood of protest in post-conflict society.    

<center>
[Figure 3: Negative Binomial Regression Model 2](C:\Users\Megan\Documents\CMPSPaper\Figure3)
<center>

##Conclusion
	When civil conflict ends, societies increasingly rely on power-sharing agreements to facilitate cooperation with previously excluded groups in society.  However, the effects of these agreements on post-conflict behavior is unclear.  Agreements are designed to promote democratic ideals such as political inclusion, yet are not always well received or successful.  Rebel and government elites make these deals, and may lose the support of their bases.  Populations may not be willing to accept former rebels in political roles, and former rebels may be unwilling to follow leadership into legitimate political life.  Differences in rebel group wartime experience can shed some light on possible influences to resistance or acceptance of power-sharing governments.
	This research shows that power-sharing generally decreases the likelihood of post-conflict protests.  This seems to indicate that such agreements do what is expected of them; with inclusion comes less domestic strife.  However, not all rebel groups are the same.  Rebels who held wartime elections may present additional challenges to post-conflict states.  Agreements with these rebels is more likely to generate protests, though it is unclear from this data if it is former rebels, non-rebel citizens, or both protesting.  Future research should consider whether these societies are more likely to experience conflict recurrence, to help us understand whether the protests are a sign of healthy democratic expression or coming turmoil.  Electoral participation may also help to clarify the depth of support for both sides in power-sharing governments.
	The rate of power-sharing continues to increase across the world, making it necessary to study and understand the ramifications.  Providing militant organizations with political power can be a risky and obstacle-laden path, but it may also be the only way to truly resolve underlying concerns from excluded members of society.  If power-sharing governments are to be successful going forward, we must continue to delve into the conditions that they create.  







## Citations
Want to cite something?

1. Find your cite key in your bib file.
1. Put an @ before it, like @Solt2017, or whatever it is
1. @Solt2017 creates an in-text citation
1. [@Herndon2014] creates a parenthetical citation

As @Gelman2014 note, the garden of forking paths can pose problems for researchers even when they are acting in good faith.

## Other Common Things

> This will create a block quote, if you want one.
Dropping a footnote is easy.^[See? Not hard at all.]

